### ISSUE TITLE
Class 'RainLab\Translate\Behaviors\TranslatableModel' not found

### ISSUE THREAD

**Issue by XIOLog** [Magiczne/october-resume#1]
Hello.

I got an error Class 'RainLab\Translate\Behaviors\TranslatableModel' not found. How can I fix it?

**Comment by XIOLog** [comment]
I found a solution. Just need to install "RainLab\Translate" :-)

**Comment by Magiczne** [comment]
@XIOLog it's good you found solution, but the plugin should work without it fine to. I'll take a look into it tommorow.
